#!/usr/bin/env bash
## Install nginx web server and configure redirection to another web

# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html

# redirect
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;/" /etc/nginx/sites-available/default
### Start service nginx.
sudo service nginx restart
