#!/usr/bin/env sh
# install load balancer in server

# instalation of haproxy

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get install haproxy=2.4.

# dar permisos a la carpeta para que echo funcione
sudo chown -R ubuntu /etc/haproxy/
sudo chown -R ubuntu /etc/haproxy/haproxy.cfg

# configuration
echo "\nfrontend my_frontend\n\
\tbind 0.0.0.0:80\n\
\tmode http\n\
\tdefault_backends my_backend\n" >> /etc/haproxy/haproxy.cfg

echo "\nbackend my_backend\n\
\tbalance roundrobin\n\
\tserver 3669-web-01 35.185.21.233:80 check\n\
\tserver 3669-web-02 35.172.200.220:80 check\n" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
