#!/usr/bin/env bash
# MySQL backup script

passwd=$1
user='root'
sqlfile='backup.sql'
tagFileName=$(date +%d-%m-%Y).tar.gz


# create a backup
sudo mysqldump -u $user -p $passwd --all-databases > '/tmp/$sqlfile'

# compress backup
sudo tar -zcvf $tagFileName '/tmp/$sqlfile'
