#!/usr/bin/env bash
# fix ports
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server/' example #/etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/' example #/etc/nginx/sites-enabled/default
