#!/usr/bin/env bash
# loop that displays best school 10 times, except for 9th iteration 
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    i=$(( i + 1 ))
done
