#!/usr/bin/env bash
# script that displays content of the current directory, displays only content after first -

for filepath in *
do
    filename=$( cut -d '-' -f 2- <<< $filepath )
    echo $filename
done
